config/routes.rb
Readerd::Application.routes.draw do
  devise_for :users

  resources :entries

  resources :categories

  resources :feeds
  post "feeds/confirm" => 'feeds#confirm', :as => 'confirm'

  get "root/index"
  root :to => 'root#index'
  post '/' => 'root#feed_update'

  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  require 'check_url'
  include CheckURL
  belongs_to :category
  has_many :entries
  
  #validates :url, :presence => true, :null => false
  validates :url, :presence => {:null => true}

  validate :url_check
  def url_check
    res = check_url(self.url)
    if res == false && self.url != ""
      errors.add(:url, "Invalid")
    end
    get_url=Feed.where(:url => "#{url}").first rescue get_url = nil
    url_id = get_url.id rescue url_id = nil
    url_entry = Entry.where(:feed_id => "#{url_id}").first rescue url_entry = nil
    if url_id != nil && url_entry == nil
    #if url_id != nil
      errors.add(:url, "already exist")
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  require 'fetch_feed'
  require 'url_analyze'
  require 'feed_analyze'
  require 'check_url'
  include CheckURL
  include FetchFeed
  include UrlAnalyze
  include FeedAnalyze
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  #before_action :set_feed, only: [:edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    #@feeds = Feed.all
    @feeds = Feed.all.order('title ASC')

    respond_to do |format|
      format.html
      format.json { render :json => {
        :feeds => @feeds
      }}
    end

  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    #@feed = Feed.find(params[:id])
    @feeds = Feed.all.order('title ASC')
    @entries = @feed.entries.includes([:feed]).page(params[:page]).order('published_at DESC').per(16)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=>{
        #:feed    => @feed,
        :feeds    => @feeds,
        :category => @category,
        :entries  => @entries
      }}
    end
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
    @feeds = Feed.all.order('title ASC')
    respond_to do |format|
      format.html
      format.json { render :json => {
        :feed  => @feed,
        :feeds => @feeds
      }}
    end
  end

  # GET /feeds/1/edit
  def edit
    @feeds = Feed.all.order('title ASC')
    respond_to do |format|
      format.html
      format.json { render :json => {
        :feeds => @feeds
      }}
    end
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feeds = Feed.all.order('title ASC')
    @feedtmp = url_analyze(@feed.url)

    unless params[:feedurl].blank?
      @feed.feed_url=params["feedurl"]["0"]

      @feed.title, @feed.url, @feed.feed_url, @feed.last_modified = feed_analyze(@feed.feed_url)
      respond_to do |format|
        if @feed.save
          feed_fetch
          format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
	      format.json { render action: 'show', status: :created, location: @feed, :json => { :feed  => @feed, :feeds => @feeds } }
        else
          format.html { render action: 'new' }
	      format.json { render json: @feed.errors, status: :unprocessable_entity, :json => { :feed  => @feed, :feeds => @feeds } }
        end
      end
    else
      respond_to do |format|
        res = check_url(@feed.url)
        # 空白でないとき
        unless params["feed"]["url"].blank?
          if res == true
            format.html { render action: 'confirm' }
            format.json { render json: @feed.errors, status: :unprocessable_entity, :json => { :feed  => @feed, :feeds => @feeds } }
          else
            #flash.now[:error] = "URL is invalid"
            flash.now[:alert] = "URL is invalid"
            #flash.now[:notice] = "URL is invalid"
            format.html { render action: 'new'}
	        format.json { render json: @feed.errors, status: :unprocessable_entity, :json => { :feed  => @feed, :feeds => @feeds } }
          end
        else
          #flash.now[:error] = "URL is blank"
          flash.now[:alert] = "URL is blank"
          format.html { render action: 'new' }
	      format.json { render json: @feed.errors, status: :unprocessable_entity, :json => { :feed  => @feed, :feeds => @feeds } }
        end
      end
    end

  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    @feeds = Feed.all.order('title ASC')
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.', :json => { :feeds => @feeds }}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity , :json => { :feeds => @feeds }}
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy

    feed_id =  @feed.id
    @feed.entries.where(feed_id: "#{feed_id}").destroy_all

    respond_to do |format|
      format.html { redirect_to "/",  notice: 'Feed was successfully deleted' }
      format.json { head :no_content }
    end
  end

  def confirm
    @feed=params[:feedurl]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title, :url, :feed_url, :category_id, :last_modified) if params[:feed]
      #params.require(:feed).permit(:title, :url, :feed_url, :category_id, :last_modified)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_confirm.html.haml
%h1 test
/%ul
-#%dl
  - @feedarry[0][0].map | v |
    = v

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url, :size => '1024'
  .field
    = f.label :feed_url
    = f.text_field :feed_url
  -#.field
    = f.label :category_id
    = f.number_field :category_id
  .field
    = f.label :last_modified
    = f.datetime_select :last_modified
  -#.actions
    = f.submit 'Save'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    /= f.submit nil, :class => 'btn btn-mini btn-primary'
    /- if request.referer.include?("?")
    = link_to t('.cancel', :default => t("helpers.links.cancel")), :back , :class => 'btn'
    /= link_to t('.cancel', :default => t("helpers.links.cancel")), feeds_path, :class => 'btn'
    /= link_to t('.cancel', :default => t("helpers.links.cancel")), feeds_path, :class => 'btn btn-mini'

app/views/feeds/_form_add.html.haml
/= form_for @feed, method:confirm  do |f|
/= form_for [ :confirm, @feed ] do |f|
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h3= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  /%p#notice= notice
  /%p#notice= alert
  %p#error= alert
  .field
    = f.label :url
    = f.text_field :url, :size => 1024, :value => "http://"
    /= f.text_field :url, :size => 1024
    /= f.submit, render :partial => "confirm" , :class => 'btn btn-primary'
    /= f.submit nil, :class => 'btn btn-primary', render :partial => "confirm"
  .actions
    /= render :action => "confirm", :layout => false
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), "/", :class => 'btn'
    /= render :partial => "confirm"

app/views/feeds/confirm.html.haml
- model_class = Feed
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h3= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  %dl
    %font(size="3px")
      - @feedtmp.each do |feed1, feed2, feed3, feed4 |
        %dd.site
          .field
            /= radio_button :feedurl, 0, feed3
            = radio_button :feedurl, 0, feed3
            = link_to feed3
          .actions
            = f.submit nil, :class => 'btn btn-primary', :name=> 'feed_url'
            = link_to t('.cancel', :default => t("helpers.links.cancel")), "/", :class => 'btn'

app/views/feeds/edit.html.haml
- model_class = Feed
.page-header
  %h3 登録フィード情報編集
  /%h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

/%h1 Editing feed

/= render 'form'

/= link_to 'Show', @feed
/\|
/= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
- model_class = Feed
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

%h3 登録フィード一覧

= link_to t('.new', :default => t("helpers.links.new")), new_feed_path, :class => 'btn btn-primary'
%br
%ul
%dl
  %font(size="3px")
    - @feeds.each do |feed|
      %dd.site
        %img{:src => 'http://www.google.com/s2/favicons?domain='+feed.url+''}
        = link_to feed.title, feed

app/views/feeds/new.html.haml
- model_class = Feed
.page-header
  %h3 フィード新規登録
  /%h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form_add"
/= render :partial => "confirm"

/%h1 New feed

/= render 'form'
/= render 'form_add'

/= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
- model_class = Feed
%p#notice= notice
.page-header

%h3 登録フィード記事一覧
%p
  %b Title:
  = @feed.title
%p
  %b Url:
  = @feed.url
%p
  %b Feed url:
  = @feed.feed_url
-#%p
  %b Category:
  = @feed.category_id
%p
  %b Last modified:
  = @feed.last_modified

%br
= link_to t('.edit', :default => t("helpers.links.edit")), edit_feed_path, :class => 'btn btn-primary'
= link_to t('.destroy', :default => t("helpers.links.destroy")), feed_path, :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
= link_to t('.cancel', :default => t("helpers.links.cancel")), "/" , :class => 'btn'
%br
%br

= render :file => 'layouts/common/feed_entry'