config/routes.rb
Readerd::Application.routes.draw do
  devise_for :users

  resources :entries

  resources :categories

  resources :feeds
  post "feeds/confirm" => 'feeds#confirm', :as => 'confirm'

  get "root/index"
  root :to => 'root#index'
  post '/' => 'root#feed_update'

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  #belongs_to :feed, :include => :category
  #belongs_to :feed, :polymorphic => :category
  #belongs_to :feed, :polymorphic => :category, :foreign_key => "id"
  belongs_to :feed, :polymorphic => :category
  delegate :category, :to => :feed, :allow_nil => true

  ### kaminari
  #default_scope :order => 'published_at DESC'
  default_scope -> { order( 'published_at DESC') }
  paginates_per 60
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @feeds = Feed.all
    #@entries = Entry.all
    #@entries = Entry.includes([:feed])
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:feed_id, :title, :url, :summary, :published_at)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :feed_id
    = f.number_field :feed_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :published_at
    = f.datetime_select :published_at
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%h1 Listing entries

%table
  %tr
    %th Feed
    %th Title
    %th Url
    %th Summary
    %th Published at
    %th
    %th
    %th

  - @entries.each do |entry|
    %tr
      %td= entry.feed_id
      %td= entry.title
      %td= entry.url
      %td= entry.summary
      %td= entry.published_at
      %td= link_to 'Show', entry
      %td= link_to 'Edit', edit_entry_path(entry)
      %td= link_to 'Destroy', entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Feed:
  = @entry.feed_id
%p
  %b Title:
  = @entry.title
%p
  %b Url:
  = @entry.url
%p
  %b Summary:
  = @entry.summary
%p
  %b Published at:
  = @entry.published_at

= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Back', entries_path